// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFKwZtlhljOsEXh_VwLLyyCS-mgaHi3pA',
    appId: '1:923927006659:web:d546539e6fbfeb4ca6c176',
    messagingSenderId: '923927006659',
    projectId: 'r2re-75417',
    authDomain: 'r2re-75417.firebaseapp.com',
    storageBucket: 'r2re-75417.appspot.com',
    measurementId: 'G-VW2070LKFX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLDE43QktyeFdRtkm1RHArUZy9PzEadf4',
    appId: '1:923927006659:android:51848c271d59ce1fa6c176',
    messagingSenderId: '923927006659',
    projectId: 'r2re-75417',
    storageBucket: 'r2re-75417.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMC-dDEt_6hxYdSlYht4LQBW1wbEBsLF4',
    appId: '1:923927006659:ios:e92de7756cb8b79fa6c176',
    messagingSenderId: '923927006659',
    projectId: 'r2re-75417',
    storageBucket: 'r2re-75417.appspot.com',
    androidClientId: '923927006659-c7hv07rvv363q4v5i6mof3nbuhhakn8k.apps.googleusercontent.com',
    iosClientId: '923927006659-clfnin48m4rek3sjfph6laua9sd8pf1o.apps.googleusercontent.com',
    iosBundleId: 'com.r2rekorea.r2reowner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMC-dDEt_6hxYdSlYht4LQBW1wbEBsLF4',
    appId: '1:923927006659:ios:75eb715db11d8e48a6c176',
    messagingSenderId: '923927006659',
    projectId: 'r2re-75417',
    storageBucket: 'r2re-75417.appspot.com',
    androidClientId: '923927006659-c7hv07rvv363q4v5i6mof3nbuhhakn8k.apps.googleusercontent.com',
    iosClientId: '923927006659-v175tafd0m5u4tpksc928vt8psvh6pfr.apps.googleusercontent.com',
    iosBundleId: 'com.r2rekorea.r2reowner.RunnerTests',
  );
}
